#!/bin/bash
#PBS -N scenic_aucell
#PBS -o scenic_aucell.out
#PBS -e scenic_aucell.err
#PBS -m bea
#PBS -M ao225@ic.ac.uk
#PBS -l select=1:ncpus=26:mem=128gb
#PBS -l walltime=12:00:00
 
module load miniforge/3
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate ml_age

python /rds/general/user/ao225/home/CardiaFinal/Code/Science/SCENIC_job/AUCELL.py
 
